on: [push]
name: Build image and Deploy container

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -f src/Server/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/blazor8app:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/blazor8app:${{ github.sha }}
            
        - name: 'Build and deploy Container App'
          uses: azure/container-apps-deploy-action@v1
          with:
             acrName: ${{ secrets.REGISTRY_USERNAME }}
             acrUsername: ${{ secrets.REGISTRY_USERNAME }}
             acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
             imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/blazor8app:${{ github.sha }}
             containerAppName: blazor8app
             resourceGroup: ${{ secrets.RESOURCE_GROUP }}
             location: 'swedencentral'
             targetPort: 8080
